package com.graphqueryengine.mapping;
import org.junit.jupiter.api.Test;
import java.util.Map;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
class MappingStoreTest {
    private static MappingConfig cfg(String label) {
        return new MappingConfig(
                Map.of(label, new VertexMapping("tbl", "id", Map.of("name", "name"))),
                Map.of()
        );
    }
    @Test
    void putAndGetActive() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        Optional<MappingStore.StoredMapping> active = store.getActive();
        assertTrue(active.isPresent());
        assertEquals("m1", active.get().id());
        assertEquals("First", active.get().name());
    }
    @Test
    void secondPutWithoutActivateDoesNotChangeActive() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        assertEquals("m1", store.activeMappingId().orElse(null));
    }
    @Test
    void secondPutWithActivateChangesActive() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), true);
        assertEquals("m2", store.activeMappingId().orElse(null));
    }
    @Test
    void getByIdReturnsCorrectMapping() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        Optional<MappingStore.StoredMapping> m2 = store.getById("m2");
        assertTrue(m2.isPresent());
        assertEquals("Second", m2.get().name());
    }
    @Test
    void getByIdReturnsEmptyForUnknown() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        assertTrue(store.getById("nonexistent").isEmpty());
    }
    @Test
    void setActiveReturnsTrueForKnownId() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        assertTrue(store.setActive("m2"));
        assertEquals("m2", store.activeMappingId().orElse(null));
    }
    @Test
    void setActiveReturnsFalseForUnknownId() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        assertFalse(store.setActive("unknown"));
        assertEquals("m1", store.activeMappingId().orElse(null));
    }
    @Test
    void deleteRemovesMappingAndClearsActiveWhenItWasActive() {
        MappingStore store = new MappingStore();
        store.put("m1", "Only", cfg("Person"), true);
        MappingStore.DeleteResult result = store.delete("m1");
        assertTrue(result.deleted());
        assertNull(result.newActiveMappingId());
        assertTrue(store.getActive().isEmpty());
    }
    @Test
    void deleteOfActivePicksFallback() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        MappingStore.DeleteResult result = store.delete("m1");
        assertTrue(result.deleted());
        assertEquals("m2", result.newActiveMappingId());
        assertEquals("m2", store.activeMappingId().orElse(null));
    }
    @Test
    void deleteOfNonActiveLeavesActiveUnchanged() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        store.delete("m2");
        assertEquals("m1", store.activeMappingId().orElse(null));
    }
    @Test
    void deleteReturnsFalseForUnknown() {
        MappingStore store = new MappingStore();
        store.put("m1", "Only", cfg("Person"), true);
        MappingStore.DeleteResult result = store.delete("ghost");
        assertFalse(result.deleted());
        assertNotNull(result.error());
    }
    @Test
    void listIncludesAllMappingsWithActiveFlag() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        store.put("m2", "Second", cfg("Car"), false);
        var list = store.list();
        assertEquals(2, list.size());
        long activeCount = list.stream().filter(MappingStore.MappingInfo::active).count();
        assertEquals(1, activeCount);
    }
    @Test
    void autoGeneratedIdWhenNullProvided() {
        MappingStore store = new MappingStore();
        MappingStore.StoredMapping stored = store.put(null, "Auto", cfg("Person"), true);
        assertNotNull(stored.id());
        assertFalse(stored.id().isBlank());
        assertTrue(stored.id().startsWith("mapping-"));
    }
    @Test
    void autoGeneratedNameFallsBackToId() {
        MappingStore store = new MappingStore();
        MappingStore.StoredMapping stored = store.put("my-id", null, cfg("Person"), true);
        assertEquals("my-id", stored.name());
    }
    @Test
    void putValidatesNullConfig() {
        MappingStore store = new MappingStore();
        assertThrows(IllegalArgumentException.class,
                () -> store.put("x", "x", null, true));
    }
    @Test
    void putValidatesEmptyVerticesAndEdges() {
        MappingStore store = new MappingStore();
        assertThrows(IllegalArgumentException.class,
                () -> store.put("x", "x", new MappingConfig(Map.of(), Map.of()), true));
    }
    @Test
    void isEmptyReturnsTrue() {
        assertTrue(new MappingStore().isEmpty());
    }
    @Test
    void isEmptyReturnsFalseAfterPut() {
        MappingStore store = new MappingStore();
        store.put("m1", "First", cfg("Person"), true);
        assertFalse(store.isEmpty());
    }
}
